/*USE myBooks;
GO
INSERT INTO Publisher VALUES ('1','The Berkley Publishing Group') 
INSERT INTO Publisher VALUES ('2','The McGraw Hill Companies') 
INSERT INTO Publisher VALUES ('3','Vintage Books') 
INSERT INTO Publisher VALUES ('4','Harper Collins Publishers') 
INSERT INTO Publisher VALUES ('5','Bloomsbury Press') 
INSERT INTO Publisher VALUES ('6','Bantam Dell') 

INSERT INTO Author VALUES ('1','Herbert','Frank')
INSERT INTO Author VALUES ('2','Patterson','Kerry') 
INSERT INTO Author VALUES ('3','Grenny','Joseph') 
INSERT INTO Author VALUES ('4','McMillan','Ron') 
INSERT INTO Author VALUES ('5','Switzler','Al') 
INSERT INTO Author VALUES ('6','Mann','Charles') 
INSERT INTO Author VALUES ('7','Gibson','William') 
INSERT INTO Author VALUES ('8','Tolkien','J.R.R') 
INSERT INTO Author VALUES ('9','Harari','Yuval') 

INSERT INTO Genres VALUES ('1','Action and adventure')
INSERT INTO Genres VALUES ('2','Alternate history')
INSERT INTO Genres VALUES ('3','Anthology')
INSERT INTO Genres VALUES ('4','Art')
INSERT INTO Genres VALUES ('5','Autobiography')
INSERT INTO Genres VALUES ('6','Biography')
INSERT INTO Genres VALUES ('7','Book review')
INSERT INTO Genres VALUES ('8','Chick lit')
INSERT INTO Genres VALUES ('9','Childrens')
INSERT INTO Genres VALUES ('10','Comic book')
INSERT INTO Genres VALUES ('11','Coming-of-age')
INSERT INTO Genres VALUES ('12','Cookbook')
INSERT INTO Genres VALUES ('13','Crime')
INSERT INTO Genres VALUES ('14','Diary')
INSERT INTO Genres VALUES ('15','Dictionary')
INSERT INTO Genres VALUES ('16','Drama')
INSERT INTO Genres VALUES ('17','Encyclopedia')
INSERT INTO Genres VALUES ('18','Fairytale')
INSERT INTO Genres VALUES ('19','Fantasy')
INSERT INTO Genres VALUES ('20','Graphic novel')
INSERT INTO Genres VALUES ('21','Guide')
INSERT INTO Genres VALUES ('22','Health')
INSERT INTO Genres VALUES ('23','Historical fiction')
INSERT INTO Genres VALUES ('24','History')
INSERT INTO Genres VALUES ('25','Horror')
INSERT INTO Genres VALUES ('26','Journal')
INSERT INTO Genres VALUES ('27','Math')
INSERT INTO Genres VALUES ('28','Memoir')
INSERT INTO Genres VALUES ('29','Mystery')
INSERT INTO Genres VALUES ('30','Paranormal romance')
INSERT INTO Genres VALUES ('31','Picture book')
INSERT INTO Genres VALUES ('32','Poetry')
INSERT INTO Genres VALUES ('33','Political thriller')
INSERT INTO Genres VALUES ('34','Prayer')
INSERT INTO Genres VALUES ('35','Religion, spirituality, and new age')
INSERT INTO Genres VALUES ('36','Review')
INSERT INTO Genres VALUES ('37','Romance')
INSERT INTO Genres VALUES ('38','Satire')
INSERT INTO Genres VALUES ('39','Science')
INSERT INTO Genres VALUES ('40','Science fiction')
INSERT INTO Genres VALUES ('41','Self help')
INSERT INTO Genres VALUES ('42','Short story')
INSERT INTO Genres VALUES ('43','Suspense')
INSERT INTO Genres VALUES ('44','Textbook')
INSERT INTO Genres VALUES ('45','Thriller')
INSERT INTO Genres VALUES ('46','Travel')
INSERT INTO Genres VALUES ('47','True crime')
INSERT INTO Genres VALUES ('48','Young adult')

INSERT INTO Book VALUES ('1','Dune','1965','1','9.5')
INSERT INTO Book VALUES ('2','Crucial Conversations','2012','2','7.3')
INSERT INTO Book VALUES ('3','1491','2006','3','8.5')
INSERT INTO Book VALUES ('4','Neuromancer','1986','1','6.8')
INSERT INTO Book VALUES ('5','The Lord of the Rings','1954','4','9.2')
INSERT INTO Book VALUES ('6','Sapiens','2015','4','8.6')

INSERT INTO BookGenres VALUES ('1','40')
INSERT INTO BookGenres VALUES ('2','41')
INSERT INTO BookGenres VALUES ('3','24')
INSERT INTO BookGenres VALUES ('4','40')
INSERT INTO BookGenres VALUES ('5','40')
INSERT INTO BookGenres VALUES ('6','24')

INSERT INTO BookAuthors VALUES ('1','1')
INSERT INTO BookAuthors VALUES ('2','2')
INSERT INTO BookAuthors VALUES ('2','3')
INSERT INTO BookAuthors VALUES ('2','4')
INSERT INTO BookAuthors VALUES ('2','5')
INSERT INTO BookAuthors VALUES ('3','6')
INSERT INTO BookAuthors VALUES ('4','7')
INSERT INTO BookAuthors VALUES ('5','8')
INSERT INTO BookAuthors VALUES ('6','9')*/
 







