USE [master]
GO
/****** Object:  Database [myBooks]    Script Date: 3/1/2020 10:32:21 PM ******/
CREATE DATABASE [myBooks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'myBooks', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\myBooks.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'myBooks_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\myBooks_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [myBooks] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [myBooks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [myBooks] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [myBooks] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [myBooks] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [myBooks] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [myBooks] SET ARITHABORT OFF 
GO
ALTER DATABASE [myBooks] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [myBooks] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [myBooks] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [myBooks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [myBooks] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [myBooks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [myBooks] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [myBooks] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [myBooks] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [myBooks] SET  ENABLE_BROKER 
GO
ALTER DATABASE [myBooks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [myBooks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [myBooks] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [myBooks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [myBooks] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [myBooks] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [myBooks] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [myBooks] SET RECOVERY FULL 
GO
ALTER DATABASE [myBooks] SET  MULTI_USER 
GO
ALTER DATABASE [myBooks] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [myBooks] SET DB_CHAINING OFF 
GO
ALTER DATABASE [myBooks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [myBooks] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [myBooks] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'myBooks', N'ON'
GO
ALTER DATABASE [myBooks] SET QUERY_STORE = OFF
GO
USE [myBooks]
GO
/****** Object:  Table [dbo].[Author]    Script Date: 3/1/2020 10:32:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Author](
	[au_id] [int] NOT NULL,
	[au_lname] [varchar](50) NOT NULL,
	[au_fname] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[au_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Book]    Script Date: 3/1/2020 10:32:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book](
	[bk_id] [int] NOT NULL,
	[title] [varchar](50) NULL,
	[publish_date] [datetime] NULL,
	[pu_id] [int] NOT NULL,
	[rating] [decimal](18, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[bk_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BookAuthors]    Script Date: 3/1/2020 10:32:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookAuthors](
	[bk_id] [int] NOT NULL,
	[au_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[bk_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BookGenres]    Script Date: 3/1/2020 10:32:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookGenres](
	[bk_id] [int] NOT NULL,
	[gn_id] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[gn_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Genres]    Script Date: 3/1/2020 10:32:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Genres](
	[gn_id] [int] NOT NULL,
	[genre] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[gn_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Publisher]    Script Date: 3/1/2020 10:32:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Publisher](
	[pub_id] [int] NOT NULL,
	[pub_name] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[pub_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [idx_pu_id]    Script Date: 3/1/2020 10:32:22 PM ******/
CREATE NONCLUSTERED INDEX [idx_pu_id] ON [dbo].[Book]
(
	[pu_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [idx_au_id]    Script Date: 3/1/2020 10:32:22 PM ******/
CREATE NONCLUSTERED INDEX [idx_au_id] ON [dbo].[BookAuthors]
(
	[au_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [idx_bk_id2]    Script Date: 3/1/2020 10:32:22 PM ******/
CREATE NONCLUSTERED INDEX [idx_bk_id2] ON [dbo].[BookAuthors]
(
	[bk_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [idx_bk_id]    Script Date: 3/1/2020 10:32:22 PM ******/
CREATE NONCLUSTERED INDEX [idx_bk_id] ON [dbo].[BookGenres]
(
	[bk_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [idx_gn_id]    Script Date: 3/1/2020 10:32:22 PM ******/
CREATE NONCLUSTERED INDEX [idx_gn_id] ON [dbo].[BookGenres]
(
	[gn_id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [FK_pu_id] FOREIGN KEY([pu_id])
REFERENCES [dbo].[Publisher] ([pub_id])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [FK_pu_id]
GO
ALTER TABLE [dbo].[BookAuthors]  WITH CHECK ADD  CONSTRAINT [FK_au_id] FOREIGN KEY([au_id])
REFERENCES [dbo].[Author] ([au_id])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[BookAuthors] CHECK CONSTRAINT [FK_au_id]
GO
ALTER TABLE [dbo].[BookAuthors]  WITH CHECK ADD  CONSTRAINT [FK_bk_id2] FOREIGN KEY([bk_id])
REFERENCES [dbo].[Book] ([bk_id])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[BookAuthors] CHECK CONSTRAINT [FK_bk_id2]
GO
ALTER TABLE [dbo].[BookGenres]  WITH CHECK ADD  CONSTRAINT [FK_bk_id] FOREIGN KEY([bk_id])
REFERENCES [dbo].[Book] ([bk_id])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[BookGenres] CHECK CONSTRAINT [FK_bk_id]
GO
ALTER TABLE [dbo].[BookGenres]  WITH CHECK ADD  CONSTRAINT [FK_gn_id] FOREIGN KEY([gn_id])
REFERENCES [dbo].[Genres] ([gn_id])
ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[BookGenres] CHECK CONSTRAINT [FK_gn_id]
GO
USE [master]
GO
ALTER DATABASE [myBooks] SET  READ_WRITE 
GO
